### PR TITLE
[0.17] Port https://github.com/knative/eventing-contrib/pull/1631

### PR DESCRIPTION
**Pull request by aliok**
Port https://github.com/knative/eventing-contrib/pull/1631 here in 0.17 of our fork

### CODE REVIEW

**Comment by aliok** [comment]
/hold
Let's wait until https://github.com/knative/eventing-contrib/pull/1631 is merged

**Comment by aliok** [comment]
/unhold

cc @matzew upstream PR, https://github.com/knative/eventing-contrib/pull/1631, is merged

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
I think https://github.com/openshift/knative-eventing-contrib/pull/578 will the CI

**Comment by aliok** [comment]
Rebased, need to rebase once again when https://github.com/openshift/knative-eventing-contrib/pull/582 is merged to master

**Pull request merged**
