### PR TITLE
CI WAS HERE 

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by alanfx** [comment]
I know these PRs are easy to create, but you can also just hit this URL to trigger the Jenkins job: https://ocf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/knative-eventing-fork-nightly-ci/build?token=WeAreRedHat

**Comment by matzew** [comment]
@alanfx but. this is the release-0.8.1 branch - not release-next

**Comment by alanfx** [comment]
@matzew ok, ignore my comment then!

**Pull request merged**
