### PR TITLE
[0.17] Create temporary tracing config in /tmp

### PR DESCRIPTION
**Pull request by aliok**
Getting permission denied when eventing-contrib e2e tests are run by S-O
Context: https://github.com/openshift-knative/serverless-operator/pull/520#issuecomment-705411536

To be ported to 0.18 and master later

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
/hold
@mgencur has a better idea

**Comment by aliok** [comment]
@mgencur can you review please?

**Comment by aliok** [comment]
Also fixes https://github.com/openshift-knative/serverless-operator/pull/520#issuecomment-705852887

**Comment by aliok** [comment]
Again, some pod is not coming up, but I can't see the logs for that pod in Prow artifacts.
Gonna try locally, but I am not hopeful

**Comment by aliok** [comment]
/close

Closing in favor of https://github.com/openshift/knative-eventing-contrib/pull/582

**Pull request closed without merging**
