### PR TITLE
[0.17] Backport https://github.com/knative/pkg/pull/1842

### PR DESCRIPTION
**Pull request by aliok**
Backport https://github.com/knative/pkg/pull/1842

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
/hold

as said in https://github.com/openshift/knative-eventing/pull/912  let's see if we can land the upstream fix

**Comment by aliok** [comment]
@lberk @matzew 
https://github.com/knative/pkg/pull/1842 is merged and `go get -u knative.dev/pkg@release-0.17` did the trick.

Please review and `unhold`

**Comment by aliok** [comment]
/retest 
wtf

**Pull request merged**
