### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by matzew** [comment]
@lberk   like mentioned on the slack channel,

looks like serving times out, looking at the log

```
DEBUG 01:27:11.191 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (865/900)...
DEBUG 01:27:16.983 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (870/900)...
DEBUG 01:27:22.831 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (875/900)...
DEBUG 01:27:28.627 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (880/900)...
DEBUG 01:27:34.440 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (885/900)...
DEBUG 01:27:40.292 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (890/900)...
DEBUG 01:27:46.064 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (895/900)...
DEBUG 01:27:51.992 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (900/900)...
DEBUG 01:27:57.906 Execution failed: [[ $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") != True ]]. Waiting 5 sec (905/900)...
ERROR 01:28:02.908 Time out of 900 exceeded
+ failed=1
+ popd
```

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
